### PR TITLE
Add quick start guide; Address #7.

### PR DESCRIPTION
**Pull request by ruebot**

### CODE REVIEW

**Comment by edf** [comment]
seems like it built successfully on my Linux desktop!  A minor issue, in README.md under Under Quick Start, please change
1. git submodule update --init --recursive
2. cd claw-docker/commands

to
1. cd claw-docker
2. git submodule update --init --recursive
3. cd commands

**Comment by edf** [comment]
Should mention that docker-compose needs to be installed (at least on Ubuntu 14.04)

**Comment by edf** [comment]
Probably.  I am going to try again to make sure the steps work as documented.

**Comment by nigelgbanks** [comment]
Minor point, could we keep the line length under 80 columns where possible, it makes it easier to read from the terminal, etc.

**Comment by nigelgbanks** [comment]
Another small point of consistency; changing the headers makes the README.md different from all the other Docker repositories, probably should change the other README.md as well to match.

**Comment by nigelgbanks** [comment]
Cool, one more thing. Perhaps we should just renmae docker-compose.yml to example.docker-compose.yml and include in the quick-start to copy it to docker-compose.yml so no accidentally commits their configuration, and folks can choose appropriate ports and volumes.

**Pull request merged**
